
#Settings affecting the logical server side.
[server]

	#Opt-out settings
	[server.optout]
		#Disable possibility to sit on stools and chairs.
		without_chair_sitting = false
		#Opt-out any block by its registry name ('*' wildcard matching, comma separated list, whitespaces ignored. You must match the whole name, means maybe add '*' also at the begin and end. Example: '*wood*,*steel*' excludes everything that has 'wood' or 'steel' in the registry name. The matching result is also traced in the log file. 
		pattern_excludes = ""
		#Disable the speed boost of ladders in this mod.
		without_ladder_speed_boost = false
		#Prevent blocks from being opt'ed by registry name ('*' wildcard matching, comma separated list, whitespaces ignored. Evaluated before all other opt-out checks. You must match the whole name, means maybe add '*' also at the begin and end. Example: '*wood*,*steel*' includes everything that has 'wood' or 'steel' in the registry name.The matching result is also traced in the log file.
		pattern_includes = ""
		#Disable history refabrication feature of the crafting table.
		without_crafting_table_history = false

	#Miscellaneous settings
	[server.miscellaneous]
		#Disable directly picking up layers from slabs and slab  slices by left clicking while looking up/down.
		without_direct_slab_pickup = true
		#Enables experimental features. Use at own risk.
		with_experimental = false
		#Disables increasing/decreasing the crafting grid items by scrolling over the crafting result slot.
		without_crafting_mouse_scrolling = false
		#Enable debug log messages for trouble shooting. Don't activate if not really needed, this can spam the log file.
		with_debug_logging = false
		#Disable all TERs (tile entity renderers).
		without_ters = false

